"use client"

import { Sandpack } from "@codesandbox/sandpack-react"
import { X, Maximize2, Minimize2 } from "lucide-react"
import { useState } from "react"

interface CodePreviewProps {
  code?: string
  language?: string
  files?: Record<string, string>
  onClose: () => void
}

function detectTemplate(language: string, code: string): "react" | "vanilla" | "static" {
  const lang = language.toLowerCase()
  if (
    lang.includes("jsx") ||
    lang.includes("react") ||
    lang.includes("tsx") ||
    code.includes("useState") ||
    code.includes("export default function") ||
    code.includes("import React")
  ) {
    return "react"
  }
  if (lang.includes("html")) {
    return "static"
  }
  return "vanilla"
}

export default function CodePreview({ code, language, files, onClose }: CodePreviewProps) {
  const [expanded, setExpanded] = useState(false)

  let template: "react" | "vanilla" | "static"
  let finalFiles: Record<string, string>

  if (files) {
    // ── Multi-file project mode — real project generated by the code engine ──
    const hasHtml = Object.keys(files).some((p) => p.toLowerCase().endsWith(".html"))
    template = hasHtml ? "static" : "react"
    finalFiles = { ...files }

    if (template === "react") {
      if (!finalFiles["/index.js"]) {
        finalFiles["/index.js"] = `
import React from "react"
import ReactDOM from "react-dom/client"
import "./styles.css"
import App from "./App"

const root = ReactDOM.createRoot(document.getElementById("root"))
root.render(<App />)
`
      }
      if (!finalFiles["/styles.css"]) {
        finalFiles["/styles.css"] = `
@tailwind base;
@tailwind components;
@tailwind utilities;
`
      }
    }
  } else {
    // ── Legacy single-block mode (older messages, or non-code-mode previews) ──
    template = detectTemplate(language ?? "", code ?? "")

    if (template === "react") {
      const src = code ?? ""
      const hasImport = src.includes("import")
      const hasExport = src.includes("export default")
      let appCode = src
      if (!hasImport) appCode = `import { useState, useEffect } from "react"\n\n${appCode}`
      if (!hasExport) appCode = `${appCode}\n\nexport default App`

      finalFiles = {
        "/App.js": appCode,
        "/styles.css": `
@tailwind base;
@tailwind components;
@tailwind utilities;
`,
        "/index.js": `
import React from "react"
import ReactDOM from "react-dom/client"
import "./styles.css"
import App from "./App"

const root = ReactDOM.createRoot(document.getElementById("root"))
root.render(<App />)
`,
      }
    } else if (template === "static") {
      finalFiles = { "/index.html": code ?? "" }
    } else {
      finalFiles = { "/index.js": code ?? "" }
    }
  }

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm
    flex items-center justify-center p-4">
      <div className={`bg-[#0c0c0c] border border-white/10 rounded-2xl
      overflow-hidden flex flex-col shadow-2xl
      ${expanded ? "w-full h-full" : "w-full max-w-6xl h-[85vh]"}`}>

        {/* Header */}
        <div className="flex items-center justify-between px-4 py-3
        border-b border-white/10 shrink-0">
          <div className="flex items-center gap-2">
            <div className="w-2 h-2 rounded-full bg-green-400" />
            <span className="text-sm font-medium text-white/70">
              Live Preview
            </span>
            <span className="text-xs text-white/30 px-2 py-0.5
            rounded-md bg-white/5">
              {files ? `${Object.keys(files).length} files` : language || "code"}
            </span>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => setExpanded(!expanded)}
              className="w-7 h-7 rounded-lg flex items-center
              justify-center text-white/40 hover:text-white
              hover:bg-white/10 transition-all"
            >
              {expanded ? <Minimize2 size={14} /> : <Maximize2 size={14} />}
            </button>
            <button
              onClick={onClose}
              className="w-7 h-7 rounded-lg flex items-center
              justify-center text-white/40 hover:text-white
              hover:bg-white/10 transition-all"
            >
              <X size={14} />
            </button>
          </div>
        </div>

        {/* Sandpack */}
        <div className="flex-1 overflow-hidden">
          <Sandpack
            template={template === "react" ? "react" : template === "static" ? "static" : "vanilla"}
            files={finalFiles}
            theme="dark"
            options={{
              showNavigator: false,
              showTabs: template !== "static",
              showLineNumbers: true,
              showConsole: true,
              editorWidthPercentage: 45,
              externalResources: template === "react"
                ? ["https://cdn.tailwindcss.com"]
                : []
            }}
          />
        </div>
      </div>
    </div>
  )
}